import { InterventionHandler } from '../../interventions/handler.js'
import { proceed, deny } from '../../interventions/actions.js'
import type { InterventionAction } from '../../interventions/actions.js'
import type { BeforeToolCallEvent } from '../../hooks/events.js'
import type { OnError } from '../../interventions/handler.js'
import {
  isAuthorized,
  checkParsePolicySet,
  validate,
  type CedarValueJson,
  type TypeAndId,
  type EntityJson,
} from '@cedar-policy/cedar-wasm/nodejs'
import { readFileSync, existsSync } from 'node:fs'
import * as mcpSchemaGeneratorWasm from '@cedar-policy/mcp-schema-generator-wasm'
import type { SchemaGenerator } from './schema-generator.js'
import { createSchemaGenerator } from './schema-generator.js'

/**
 * Minimal tool definition for schema generation. Matches MCP tool format.
 */
export interface ToolDefinition {
  name: string
  inputSchema?: { type: string; properties?: Record<string, CedarValueJson>; required?: string[] }
  description?: string
}

/**
 * Configuration for the {@link CedarAuthorization} intervention handler.
 *
 * @see {@link https://docs.cedarpolicy.com/syntax-policy.html | Cedar policy syntax}
 */
export interface CedarAuthorizationConfig {
  /** Cedar policy text, or a path to a `.cedar` file on disk. */
  policies: string

  /** Tool definitions (MCP format) for auto schema generation. Use with `CedarAuthorization.create()`. */
  tools?: ToolDefinition[]

  /** Entity data (array or path to `.json` file). Only needed for Cedar entity hierarchy. */
  entities?: EntityJson[] | string

  /** Cedar schema for policy validation. Auto-generated when `tools` is provided. */
  schema?: string

  /**
   * Cedar namespace for actions and resources. When set, the authorization request uses
   * namespaced types (e.g. `Agent::Action::"search"` instead of `Action::"search"`), and
   * schema generation preserves the namespace wrapper.
   *
   * Use this when your policies are generated by tools like `cedar-agent-policy-builder`
   * that produce namespaced Cedar policies.
   */
  namespace?: string

  /** Static principal. Defaults to `User::"anonymous"`. Mutually exclusive with `principalResolver`. */
  principal?: TypeAndId

  /**
   * Dynamic principal resolver for multi-tenant agents.
   * Return `undefined` to deny (fail-closed). Mutually exclusive with `principal`.
   */
  principalResolver?: ((invocationState: Record<string, unknown>) => TypeAndId | undefined) | undefined

  /**
   * Injects extra fields into `context.session`. Cannot overwrite `hour_utc` or `call_count`.
   * Use to forward `invocationState` values (role, environment, etc.) into Cedar context.
   *
   * @see {@link https://docs.cedarpolicy.com/policies/syntax-operators.html | Cedar `has` operator}
   */
  contextEnricher?:
    | ((context: {
        toolName: string
        toolInput: Record<string, unknown>
        invocationState: Record<string, unknown>
      }) => Record<string, CedarValueJson>)
    | undefined

  /**
   * Error handling: `'throw'` (default), `'deny'` (fail-closed), `'proceed'` (dangerous: fail-open).
   */
  onError?: OnError | undefined
}

/**
 * Cedar authorization intervention handler. Evaluates policies before each tool call.
 *
 * Each tool maps to: Action = tool name, Resource = unconstrained,
 * Context = `{ input: <tool args>, session: { hour_utc, call_count, ...enricher } }`.
 *
 * @see {@link https://cedarpolicy.com | Cedar} · {@link https://github.com/cedar-policy/cedar-for-agents | cedar-for-agents}
 *
 * @example
 * ```typescript
 * const cedar = new CedarAuthorization({
 *   policies: 'permit(principal, action == Action::"search", resource);',
 * })
 *
 * // With schema validation:
 * const cedar = await CedarAuthorization.create({ policies: '...', tools: [searchTool] })
 * ```
 */
export class CedarAuthorization extends InterventionHandler {
  readonly name = 'cedar-authorization'
  override readonly onError: OnError

  private _policies: string
  private _entities: EntityJson[]
  private _schema: string | undefined
  private readonly _policySource: string
  private readonly _entitySource: EntityJson[] | string | undefined
  private readonly _schemaSource: string | undefined
  private readonly _principal: TypeAndId | undefined
  private readonly _principalResolver: ((invocationState: Record<string, unknown>) => TypeAndId | undefined) | undefined
  private readonly _contextEnricher: CedarAuthorizationConfig['contextEnricher']
  private readonly _tools: ToolDefinition[] | undefined
  private readonly _schemaGenerator: SchemaGenerator | undefined
  private readonly _actionType: string
  private readonly _resourceType: string
  private readonly _resourceId: string
  private readonly _callCounts = new Map<string, number>()
  private static readonly _stateKey = 'cedar-authorization'

  constructor(config: CedarAuthorizationConfig) {
    super()
    if (config.principal && config.principalResolver) {
      throw new Error('Provide either `principal` or `principalResolver`, not both')
    }
    this._policySource = config.policies
    this._entitySource = config.entities
    this._schemaSource = config.schema
    this._policies = loadPolicies(config.policies)
    this._entities = loadEntities(config.entities)
    this._tools = config.tools
    this._schemaGenerator = config.tools ? createSchemaGenerator(mcpSchemaGeneratorWasm, config.namespace) : undefined

    // Precompute namespaced types for use in beforeToolCall
    const ns = config.namespace
    this._actionType = ns ? `${ns}::Action` : 'Action'
    this._resourceType = ns ? `${ns}::Resource` : 'Resource'
    this._resourceId = ns ? 'default' : 'agent'

    let schemaIsAutoGenerated = false
    if (config.schema) {
      this._schema = loadSchema(config.schema)
    } else if (this._schemaGenerator && config.tools) {
      this._schema = this._schemaGenerator.generateSchema(config.tools)
      schemaIsAutoGenerated = true
    } else {
      this._schema = undefined
    }

    if (config.principalResolver) {
      this._principal = undefined
    } else {
      this._principal = config.principal ?? {
        type: ns ? `${ns}::User` : 'User',
        id: 'anonymous',
      }
    }
    this._principalResolver = config.principalResolver
    this._contextEnricher = config.contextEnricher
    this.onError = config.onError ?? 'throw'

    validatePolicies(this._policies, this._schema, schemaIsAutoGenerated)
  }

  override beforeToolCall(event: BeforeToolCallEvent): InterventionAction {
    const invocationState = event.invocationState as Record<string, unknown>
    const principal = this._principal ?? this._principalResolver!(invocationState)
    if (!principal || !principal.type || !principal.id) {
      return deny('No principal identity found in invocation state')
    }

    const callCount = this._incrementCallCount(event.agent, event.toolUse.name)
    const toolInput = (event.toolUse.input ?? {}) as Record<string, CedarValueJson>

    const result = isAuthorized({
      principal,
      action: { type: this._actionType, id: event.toolUse.name },
      resource: { type: this._resourceType, id: this._resourceId },
      context: {
        input: toolInput,
        session: {
          ...(this._contextEnricher
            ? this._contextEnricher({ toolName: event.toolUse.name, toolInput, invocationState })
            : {}),
          hour_utc: new Date().getUTCHours(),
          call_count: callCount,
        },
      },
      policies: { staticPolicies: this._policies },
      entities: this._entities,
    })

    if (result.type === 'failure') {
      this._decrementCallCount(event.agent, event.toolUse.name)
      return deny(`Cedar evaluation failed: ${result.errors.map((e) => e.message).join(', ')}`)
    }

    if (result.response.decision === 'deny') {
      this._decrementCallCount(event.agent, event.toolUse.name)
      const reasons = result.response.diagnostics.reason
      const errors = result.response.diagnostics.errors.map((e) => e.error.message)
      const details = [...reasons, ...errors].filter(Boolean)
      return deny(`Access denied by Cedar policy${details.length ? `: ${details.join(', ')}` : ''}`)
    }

    return proceed()
  }

  /** Clears rate-limit call counters. */
  resetCallCounts(agent: { appState: { set: (key: string, value: unknown) => void } }): void {
    this._callCounts.clear()
    agent.appState.set(CedarAuthorization._stateKey, {})
  }

  /** Reloads policies/entities/schema from disk. Validates before committing. */
  reload(): void {
    const policies = loadPolicies(this._policySource)
    const entities = loadEntities(this._entitySource)
    let schema: string | undefined
    let schemaIsAutoGenerated = false
    if (this._schemaSource) {
      schema = loadSchema(this._schemaSource)
    } else if (this._schemaGenerator && this._tools) {
      schema = this._schemaGenerator.generateSchema(this._tools)
      schemaIsAutoGenerated = true
    }
    validatePolicies(policies, schema, schemaIsAutoGenerated)
    this._policies = policies
    this._entities = entities
    this._schema = schema
  }

  private _incrementCallCount(
    agent: { appState: { get: (key: string) => unknown; set: (key: string, value: unknown) => void } },
    toolName: string
  ): number {
    if (this._callCounts.size === 0) {
      const stored = agent.appState.get(CedarAuthorization._stateKey) as Record<string, number> | undefined
      if (stored) {
        for (const [k, v] of Object.entries(stored)) {
          this._callCounts.set(k, v)
        }
      }
    }
    const current = this._callCounts.get(toolName) ?? 0
    const next = current + 1
    this._callCounts.set(toolName, next)
    agent.appState.set(CedarAuthorization._stateKey, Object.fromEntries(this._callCounts))
    return next
  }

  private _decrementCallCount(
    agent: { appState: { set: (key: string, value: unknown) => void } },
    toolName: string
  ): void {
    const current = this._callCounts.get(toolName) ?? 0
    if (current > 0) {
      this._callCounts.set(toolName, current - 1)
      agent.appState.set(CedarAuthorization._stateKey, Object.fromEntries(this._callCounts))
    }
  }
}

function validatePolicies(policies: string, schema?: string, autoGenerated = false): void {
  const parseResult = checkParsePolicySet({ staticPolicies: policies })
  if (parseResult.type === 'failure') {
    const errors = parseResult.errors.map((e) => e.message).join(', ')
    throw new Error(`Invalid Cedar policy: ${errors}`)
  }

  if (schema) {
    const validationResult = validate({
      schema,
      policies: { staticPolicies: policies },
    })
    if (validationResult.type === 'failure') {
      const errors = validationResult.errors.map((e) => e.message).join(', ')
      throw new Error(`Cedar policy validation failed: ${errors}`)
    }
    if (validationResult.validationErrors.length > 0) {
      let errors = validationResult.validationErrors
      if (autoGenerated) {
        // Auto-generated schemas only know about tool inputs, not handler-injected session fields.
        // Only throw on action-related errors (typos in tool names).
        errors = errors.filter(
          (e) =>
            e.error.message.includes('unrecognized action') ||
            e.error.message.includes('unable to find an applicable action')
        )
      }
      if (errors.length > 0) {
        const msg = errors.map((e) => `${e.policyId}: ${e.error.message}`).join(', ')
        throw new Error(`Cedar policy validation failed: ${msg}`)
      }
    }
  }
}

function loadSchema(schema: string): string {
  if (schema.endsWith('.cedarschema')) {
    if (!existsSync(schema)) {
      throw new Error(`Cedar schema file not found: ${schema}`)
    }
    return readFileSync(schema, 'utf-8')
  }
  return schema
}

function loadPolicies(policies: string): string {
  if (policies.endsWith('.cedar')) {
    if (!existsSync(policies)) {
      throw new Error(`Cedar policy file not found: ${policies}`)
    }
    return readFileSync(policies, 'utf-8')
  }
  return policies
}

function loadEntities(entities: EntityJson[] | string | undefined): EntityJson[] {
  if (!entities) return []
  let parsed: EntityJson[]
  if (typeof entities === 'string') {
    parsed = JSON.parse(readFileSync(entities, 'utf-8')) as EntityJson[]
  } else {
    parsed = entities
  }
  for (const entity of parsed) {
    if (!entity.uid) {
      throw new Error(`Invalid entity: each entity must have a uid with type and id`)
    }
    const uid = '__entity' in entity.uid ? entity.uid.__entity : entity.uid
    if (!uid.type || !uid.id) {
      throw new Error(`Invalid entity: each entity must have a uid with type and id`)
    }
  }
  return parsed
}
